# Generated by Django 2.2.16 on 2020-09-24 20:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sobre',
            fields=[
                ('id_sobre', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('logo', models.ImageField(upload_to='')),
                ('descricao', models.TextField()),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
    ]
