# Generated by Django 2.2.16 on 2020-10-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sobre',
            name='logo',
        ),
        migrations.AddField(
            model_name='sobre',
            name='logo_br',
            field=models.ImageField(default=' ', upload_to='images'),
        ),
        migrations.AddField(
            model_name='sobre',
            name='logo_pb',
            field=models.ImageField(default=' ', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='foto',
            field=models.ImageField(upload_to='images'),
        ),
    ]
