# Generated by Django 2.2.16 on 2020-10-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20201025_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='atividades',
            field=models.ManyToManyField(to='content.Atividade'),
        ),
    ]
